<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <UseWPF>true</UseWPF>
        <ApplicationIcon>Server\Resources\Icons\app.ico</ApplicationIcon>
        <Configurations>Debug;Release</Configurations>
        <Platforms>x64</Platforms>
        <SatelliteResourceLanguages>zh-CN</SatelliteResourceLanguages>
        <AppVersion>10.13.25-safe.1</AppVersion>
        <Version>10.13.25-safe.1</Version>
        <AssemblyVersion>10.13.25.1</AssemblyVersion>
        <FileVersion>10.13.25.1</FileVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
        <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.6" />
        <PackageReference Include="log4net" Version="3.4.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.11" />
        <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
        <PackageReference Include="NvAPIWrapper.Net" Version="0.8.1.101" />
        <PackageReference Include="System.Management" Version="10.0.11" />
        <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.11" />
        <PackageReference Include="TaskScheduler" Version="2.12.2" />
        <PackageReference Include="YamlDotNet" Version="18.1.0" />
    </ItemGroup>

    <ItemGroup>
        <Page Update="src\Host\MainWindow.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Server\MainWindow.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
    </ItemGroup>
    <ItemGroup>
        <Content Include="Resources\WebRoot\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="Server\Resources\Icons\app.ico" />
        <EmbeddedResource Include="Drivers\PawnIO\PawnIO_setup.exe" LogicalName="JiaoLongControl.PawnIO.PawnIO_setup.exe" />
        <EmbeddedResource Include="Drivers\PawnIO\RyzenSMU.bin" LogicalName="JiaoLongControl.PawnIO.RyzenSMU.bin" />
        <EmbeddedResource Include="Drivers\PawnIO\AMDFamily17.bin" LogicalName="JiaoLongControl.PawnIO.AMDFamily17.bin" />
        <None Update="Drivers\PawnIO\PawnIO.LICENSE.txt">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Drivers\PawnIO\RyzenSMU.bin">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Drivers\PawnIO\AMDFamily17.bin">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Drivers\PawnIO\Nvidia.bin">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Drivers\Blding\JiaoLongDriver64.dll">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Drivers\Blding\JiaoLongDriver64.sys">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
        <ApplicationDefinition Include="Server\App.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </ApplicationDefinition>
    </ItemGroup>
    <ItemGroup>
        <None Include="App.config" />
    </ItemGroup>
    <ItemGroup>
        <Content Include="Server/Resources/WebRoot/**">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
    <ItemGroup>
      <Folder Include="low\" />
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
            <_Parameter1>AppVersion</_Parameter1>
            <_Parameter2>$(AppVersion)</_Parameter2>
        </AssemblyAttribute>
    </ItemGroup>
</Project>
